ALTER TABLE CUSTOMERS 
ALTER COLUMN LASTNAME varchar(30) NOT NULL

ALTER TABLE CUSTOMERS
ALTER COLUMN FIRSTNAME varchar(30) NOT NULL

ALTER TABLE ORDERS
ALTER COLUMN PRODUCT_NAME varchar(30) NOT NULL

ALTER TABLE ORDERS
ALTER COLUMN PRODUCT_PRICE numeric(6,2) NOT NULL

ALTER TABLE ORDERS
ALTER COLUMN DATE_ORDER DATE NOT NULL

ALTER TABLE ORDERS
ALTER COLUMN AMOUNT INT NOT NULL

ALTER TABLE ORDERS
ADD DEFAULT 1 FOR AMOUNT

ALTER TABLE ORDERS
ADD CONSTRAINT chk_order_amount CHECK(AMOUNT > 0)

CREATE INDEX idx_customer_lastname
ON CUSTOMERS(LASTNAME)