CREATE VIEW VW_ORDERS
AS
SELECT
	ORDERS.ID,
	ORDERS.DATE_ORDER,
	PRODUCTS.PRODUCT_NAME,
	PRODUCTS.PRODUCT_PRICE,
	ORDERS.ID_CUSTOMER,
	ORDERS.AMOUNT
FROM ORDERS
LEFT JOIN PRODUCTS
ON ORDERS.PRODUCT_ID = PRODUCTS.ID;

CREATE PROCEDURE sp_PRODUCT_NAME_BY_ORDERID
	@ORDER_ID INT,
	@NAME_PRODUCT VARCHAR(30) OUTPUT
AS
SELECT @NAME_PRODUCT = VW_ORDERS.PRODUCT_NAME
FROM VW_ORDERS
WHERE VW_ORDERS.ID = @ORDER_ID; 

CREATE TABLE ORDER_REG(ID INT IDENTITY(1,1) PRIMARY KEY,
	OPER_DATE DATE,
	OPER_TYPE INT,
	ORDER_ID INT);

CREATE TRIGGER t_ORDER_NEW
ON ORDERS AFTER INSERT
AS
BEGIN
	INSERT INTO ORDER_REG
		(OPER_DATE, OPER_TYPE, ORDER_ID)
	SELECT
		I.DATE_ORDER,
		1,
		I.ID
	FROM INSERTED I
END;

CREATE TRIGGER t_ORDER_EDIT
ON ORDERS AFTER UPDATE
AS
BEGIN
	INSERT INTO ORDER_REG
		(OPER_DATE, OPER_TYPE, ORDER_ID)
	SELECT
		I.DATE_ORDER,
		2,
		I.ID
	FROM inserted I
END;