ALTER TABLE ORDERS ADD FOREIGN KEY(ID_CUSTOMER) REFERENCES CUSTOMERS(ID) ON DELETE CASCADE;

SELECT ORDERS.PRODUCT_NAME, CUSTOMERS.FIRSTNAME, CUSTOMERS.LASTNAME FROM ORDERS, CUSTOMERS WHERE ORDERS.ID_CUSTOMER = CUSTOMERS.ID;

SELECT CUSTOMERS.FIRSTNAME, CUSTOMERS.LASTNAME, CUSTOMERS.ADDRESS, ORDERS.PRODUCT_NAME FROM CUSTOMERS LEFT JOIN ORDERS ON CUSTOMERS.ID = ORDERS.ID_CUSTOMER;

SELECT CUSTOMERS.FIRSTNAME, CUSTOMERS.LASTNAME, CUSTOMERS.ADDRESS, ORDERS.PRODUCT_NAME FROM CUSTOMERS LEFT JOIN ORDERS ON CUSTOMERS.ID = ORDERS.ID_CUSTOMER WHERE CUSTOMERS.ADDRESS IS NULL;

SELECT CUSTOMERS.FIRSTNAME, CUSTOMERS.LASTNAME, ORDERS.PRODUCT_NAME FROM CUSTOMERS FULL JOIN ORDERS ON CUSTOMERS.ID = ORDERS.ID_CUSTOMER;

SELECT CUSTOMERS.LASTNAME FROM CUSTOMERS LEFT JOIN ORDERS ON CUSTOMERS.ID = ORDERS.ID_CUSTOMER WHERE ORDERS.PRODUCT_NAME IS NULL;

SELECT PRODUCT_NAME, AMOUNT FROM ORDERS WHERE ID_CUSTOMER IS NULL;