INSERT INTO CUSTOMERS (ID, FIRSTNAME, LASTNAME) VALUES (7, 'Володимир','Ільницький');

INSERT INTO CUSTOMERS (ID, FIRSTNAME, LASTNAME) VALUES (8,'Петро','Овчаренко');

INSERT INTO ORDERS (ID, PRODUCT_NAME, PRODUCT_PRICE, DATE_ORDER, ID_CUSTOMER, AMOUNT) VALUES (13, 'Dell Inspiron 3542', 6750, '12/21/2015', 7, 2);

INSERT INTO ORDERS (ID, PRODUCT_NAME, PRODUCT_PRICE, DATE_ORDER, ID_CUSTOMER, AMOUNT) SELECT 14,  'Asus X553MA', 6300, '12/22/2015', CUSTOMERS.ID, 3 FROM CUSTOMERS WHERE FIRSTNAME = 'Петро' AND LASTNAME = 'Овчаренко';

UPDATE ORDERS SET AMOUNT = 5 WHERE ID = 14;

UPDATE ORDERS SET PRODUCT_PRICE = PRODUCT_PRICE - PRODUCT_PRICE * 0.1 WHERE ID = 14;

DELETE FROM ORDERS WHERE ID = 13;
