CREATE TABLE PRODUCTS(
	ID INT IDENTITY(1,1) PRIMARY KEY,
	PRODUCT_NAME VARCHAR(30) NOT NULL,
	PRODUCT_PRICE NUMERIC(6,2) NOT NULL)

ALTER TABLE ORDERS ADD PRODUCT_ID INT;

ALTER TABLE ORDERS
ADD FOREIGN KEY(PRODUCT_ID) REFERENCES PRODUCTS(ID);

ALTER TABLE ORDERS ADD TOTAL_SUM NUMERIC(10,2);

ALTER TABLE ORDERS
DROP COLUMN PRODUCT_NAME, PRODUCT_PRICE;
