SELECT PRODUCT_NAME, MAX(AMOUNT) FROM ORDERS GROUP BY PRODUCT_NAME;

SELECT PRODUCT_NAME, MIN(AMOUNT) AS MIN_AMOUNT, MAX(AMOUNT) AS MAX_AMOUNT FROM ORDERS WHERE YEAR(DATE_ORDER) = 2015 GROUP BY PRODUCT_NAME;

SELECT AVG(AMOUNT * PRODUCT_PRICE) FROM ORDERS;

SELECT COUNT(DISTINCT ID_CUSTOMER) FROM ORDERS;

SELECT PRODUCT_NAME, SUM(AMOUNT) FROM ORDERS GROUP BY PRODUCT_NAME;

SELECT PRODUCT_NAME, SUM(AMOUNT), SUM(AMOUNT * PRODUCT_PRICE) FROM ORDERS GROUP BY PRODUCT_NAME;

SELECT PRODUCT_NAME, COUNT(ID_CUSTOMER) FROM ORDERS GROUP BY PRODUCT_NAME;

SELECT COUNT(*) FROM ORDERS WHERE PRODUCT_PRICE < 10000;

SELECT CUSTOMERS.FIRSTNAME, CUSTOMERS.LASTNAME, COUNT(*) FROM CUSTOMERS JOIN ORDERS ON CUSTOMERS.ID = ORDERS.ID_CUSTOMER GROUP BY CUSTOMERS.FIRSTNAME, CUSTOMERS.LASTNAME;

SELECT CUSTOMERS.FIRSTNAME, CUSTOMERS.LASTNAME, SUM(ORDERS.PRODUCT_PRICE * ORDERS.AMOUNT) FROM CUSTOMERS JOIN ORDERS ON CUSTOMERS.ID = ORDERS.ID_CUSTOMER GROUP BY CUSTOMERS.FIRSTNAME, CUSTOMERS.LASTNAME;

