SELECT * FROM ORDERS;

SELECT * FROM CUSTOMERS;

SELECT PRODUCT_NAME, AMOUNT, DATE_ORDER FROM ORDERS;

SELECT PRODUCT_NAME, DATE_ORDER FROM ORDERS ORDER BY DATE_ORDER ASC;

SELECT DISTINCT ID_CUSTOMER FROM ORDERS;

SELECT AMOUNT FROM ORDERS WHERE PRODUCT_NAME = 'Apple MacBook Air 13';

SELECT ID_CUSTOMER, DATE_ORDER FROM ORDERS WHERE AMOUNT > 2;

SELECT * FROM ORDERS WHERE DATE_ORDER BETWEEN '01/01/2014' AND '12/31/2014';

SELECT FIRSTNAME, LASTNAME FROM CUSTOMERS WHERE LASTNAME LIKE 'K%';

SELECT FIRSTNAME, LASTNAME FROM CUSTOMERS WHERE LASTNAME LIKE '%à';

SELECT FIRSTNAME, LASTNAME FROM CUSTOMERS WHERE LASTNAME LIKE '______';

SELECT PRODUCT_NAME FROM ORDERS WHERE NOT PRODUCT_NAME IN ('Asus PU301LA', 'HP 255 G3');

SELECT LASTNAME FROM CUSTOMERS WHERE ADDRESS IS NULL;

SELECT ID, PRODUCT_NAME, AMOUNT, AMOUNT * PRODUCT_PRICE AS SUM_PAID FROM ORDERS;

SELECT * FROM ORDERS WHERE YEAR(DATE_ORDER) < 2015;
 